---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    data_bags_path: test/data_bags
    run_list:
      - recipe[envbuilder::default]
    attributes:
      envbuilder:
        owner: vagrant
        group: vagrant
        base_dir: /home/vagrant
