---
driver:
  name: docker

provisioner:
  name: chef_zero
  environments_path: test/environments
  data_bags_path: test/data_bags

platforms:
  - name: ubuntu-14.04

suites:
  - name: staging
    provisioner:
      client_rb:
        environment: certs-stg
    run_list:
      - recipe[envbuilder::default]
    attributes:
      envbuilder:
        owner: vagrant
        group: vagrant
        base_dir: /home/vagrant

  - name: production
    provisioner:
      client_rb:
        environment: certs-prod
    run_list:
      - recipe[envbuilder::default]
    attributes:
      envbuilder:
        owner: vagrant
        group: vagrant
        base_dir: /home/vagrant
